### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by tmzane** [ettle/strcase#14]
Hello 👋

I want to use this package but the latest version (`v0.1.1`) has some transitive dependencies, which I'd like to avoid. I can see that the dependencies have already been dropped in `main`. Could you please push a new tag? Thanks!

**Comment by liyanchang** [comment]
Bumped a version. v0.2.0 should work for you now.

For what it's worth, you can always pin to a specific git hash without having to wait for a repo to have a tag. Just so you don't have to be stuck in the future! e.g. the following would have added the correct line to your go.mod
```
> go get github.com/ettle/strcase@38713c761e5266d3f216d955c109504e01feb8d9
```

Thanks!
